library(monocle)
args <- commandArgs(trailingOnly= T)
#data.name <- args[1]
rdata.file <- args[1]
feature.outfile <- args[2]
response.outfile <- args[3]
mst.outfile <- args[4]

feature_type <- strsplit(strsplit(feature.outfile, "scMTL_")[[1]][2], "_")[[1]][3]
sample_type <- strsplit(strsplit(feature.outfile, "scMTL_")[[1]][2], "_")[[1]][1]

#ATAC_file_prefix <- "/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38/" # For MACS2 peak data from Kathrin
ATAC_file_prefix <- "/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38/JAMM_singleCell_ATAC_CEL_PHH/" # For JAMM peaks generated by Florian

#load(paste("/MMCI/MS/ExpRegulation/work/data/singleCell/HepG2/G_MTL/monocle/", data.name, ".RData", sep= ""))
load(rdata.file)

print("done loading the monocle file")
if(feature_type == "static"){
  tepic <- read.table("/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38_Static/2kb/Static_hg38_PromFeatures_2kb_Gene_View.txt", header= T)
  if(sample_type == "HSMM"){
    tepic <- read.table("/MMCI/MS/DEEP-liver/archive00/hg19_gencodev17/Single_Cell_TF_Annotation_2kb_Static_TEPIC_03_13_18_10_04_02_177323167_Affinties_2kb_Gene_windows.txt", header= T)
  }
}else if(feature_type == "epigenetic"){
  if(sample_type == "EndoMT"){
    tepic <- read.table("/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38/HUVEC_hg38_3kb_DNase_TEPIC_04_08_19_17_43_21_129943828_Peak_Features_Affinity_Gene_View_Filtered.txt", header= T)
  }else{
    tepic <- read.table("/MMCI/MS/DEEP-liver/work/Tools/TEPIC/Code/Feature_Stability_Paper/Integrated_Data_DNase/01_HepG2_DNase_TEPIC_05_03_17_15_04_25_Three_Peak_Based_Features_Decay_Affinity_Gene_View_Filtered_Integrated.txt", header= T)
    tepic <- tepic[, -ncol(tepic)]
  }
}else if(feature_type == "dynamic"){
  tepic <- read.table("/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38/HepG2_ChIP_Extended_hg38_3kb_Gene_View.txt", header= T, stringsAsFactors= F)
  ## remove duplicates
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacHLC"){
  tepic <- read.table("/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38/JAMM_merged_single_Cell/JAMM_ATAC_HLC_3kb_TEPIC_07_05_19_12_53_25_421001953_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacAll"){
  tepic <- read.table("/MMCI/MS/EpiregDeep2/work/Tools/TEPIC_GS/hg38/JAMM_merged_single_Cell/JAMM_ATAC_All_3kb_TEPIC_07_05_19_12_53_25_421001953_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacHLCR2"){
  #tepic <- read.table(paste(ATAC_file_prefix, "/ATAC_CEL_R2_HLC_909_3kb_TEPIC_04_10_19_09_27_39_733598393_Peak_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  tepic <- read.table(paste(ATAC_file_prefix, "/JAMM_ATAC_CEL_R2_HLC_909_3kb_TEPIC_05_03_19_09_33_28_248716596_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacHLCR3"){
  #tepic <- read.table(paste(ATAC_file_prefix, "/ATAC_CEL_R3_HLC_912_3kb_TEPIC_04_10_19_09_25_44_480319429_Peak_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  tepic <- read.table(paste(ATAC_file_prefix, "/JAMM_ATAC_CEL_R3_HLC_912_3kb_TEPIC_05_03_19_09_27_48_499437728_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacHLCR4"){
  #tepic <- read.table(paste(ATAC_file_prefix, "/ATAC_CEL_R4_HLC_915_3kb_TEPIC_04_10_19_09_22_05_061801074_Peak_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  tepic <- read.table(paste(ATAC_file_prefix, "/JAMM_ATAC_CEL_R4_HLC_915_3kb_TEPIC_05_03_19_09_21_45_061489181_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacPHHD2"){
  #tepic <- read.table(paste(ATAC_file_prefix, "/ATAC_PHH_AFJ_D2_1288_3kb_TEPIC_04_10_19_09_30_50_109230504_Peak_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  tepic <- read.table(paste(ATAC_file_prefix, "/JAMM_ATAC_PHH_AFJ_D2_1288_3kb_TEPIC_05_03_19_10_36_18_937398358_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacPHHD1"){
  #tepic <- read.table(paste(ATAC_file_prefix, "/ATAC_PHH_DJJ_D1_1287_3kb_TEPIC_04_10_19_09_33_57_245646153_Peak_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  tepic <- read.table(paste(ATAC_file_prefix, "/JAMM_ATAC_PHH_DJJ_D1_1287_3kb_TEPIC_05_06_19_13_06_20_046536308_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}else if(feature_type == "atacPHHD3"){
  #tepic <- read.table(paste(ATAC_file_prefix, "/ATAC_PHH_IAN_D3_1289_3kb_TEPIC_04_10_19_09_20_05_246513613_Peak_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  tepic <- read.table(paste(ATAC_file_prefix, "/JAMM_ATAC_PHH_IAN_D3_1289_3kb_TEPIC_05_03_19_09_19_30_576286132_Three_Peak_Based_Features_Affinity_Gene_View_Filtered.txt", sep= ""), header= T, stringsAsFactors= F)
  dupl.genes <- duplicated(tepic$geneID)
  tepic <- tepic[!dupl.genes, ]
}



print("done reading tepic data")

ensgs <- sapply(seq(nrow(fData(HSMM))), function(i)strsplit(as.character(fData(HSMM)$gene_short_name[i]), split="\\.")[[1]][1])

hit.idx <- sapply(seq(length(ensgs)), function(i)which(tepic$geneID == ensgs[i]))

tepic_reordered <- tepic[unlist(hit.idx), ]
missing.genes <- which(sapply(seq(length(hit.idx)), function(i)length(hit.idx[[i]])) == 0)
if(length(missing.genes) != 0){
  exprs_filtered <- exprs(HSMM)[-missing.genes, ]
  ensgs <- ensgs[-missing.genes]
}else{
  exprs_filtered <- exprs(HSMM)
}

monocle_MST <- HSMM_PT@auxOrderingData[[HSMM_PT@dim_reduce_type]]$pr_graph_cell_proj_tree
monocle_MST_adj <- igraph::as_adjacency_matrix(monocle_MST)

print("writing the results to file...")
#write.table(as.matrix(monocle_MST_adj), file= paste("/MMCI/MS/ExpRegulation/work/data/singleCell/HepG2/G_MTL/monocle/", data.name, "_MST_adj.txt", sep= ""), row.names= pData(HSMM)$timepoint, col.names= pData(HSMM)$timepoint)
write.table(as.matrix(monocle_MST_adj), file= mst.outfile, row.names= pData(HSMM)$timepoint, col.names= pData(HSMM)$timepoint)
print("done writing MST")

#write.table(tepic_reordered, paste("/MMCI/MS/ExpRegulation/work/data/singleCell/HepG2/G_MTL/monocle/scMTL_", data.name, "_feature.txt", sep= ""), col.names= T, row.names= F)
write.table(tepic_reordered, feature.outfile, col.names= T, row.names= F)
print("done writing features")

#write.table(exprs_filtered, paste("/MMCI/MS/ExpRegulation/work/data/singleCell/HepG2/G_MTL/monocle/scMTL_", data.name, "_response.txt", sep= ""), col.names= pData(HSMM)$timepoint, row.names= ensgs)
write.table(exprs_filtered, response.outfile, col.names= pData(HSMM)$timepoint, row.names= ensgs)
print("done writing response")
